### ISSUE TITLE
Add Build screen to Robot module

### ISSUE THREAD

**Issue by chico** [codeandrobots/codeandrobots-app#22]
1. Create a new BuildRobot screen in App/Modules/Robot, e.g. `App/Modules/Robot/BuildRobot/index.js` and `App/Modules/Robot/BuildRobot/Screen.js`
    - Reference https://github.com/codeandrobots/codeandrobots-app/tree/master/App/Modules/Robot as a similar example
    - The new BuildRobot screen should match the attached screenshot
2. Update `App/Modules/index.js` to export the BuildRobot screen
3. Add BuildRobot screen to `App/Navigation/Screens/index.js`
4. Write a module test for the BuildRobot screen

To test the module is working you can temporarily change the routeName in https://github.com/codeandrobots/codeandrobots-app/blob/master/App/Containers/StartContainer.js#L26 but remember to NOT commit that temporary change.

![Screen Shot 2019-08-09 at 18 02 11](https://user-images.githubusercontent.com/16405/62795956-d8cfbb80-bacf-11e9-8b0d-5a8eeb721f22.png)

**Comment by OsosKP** [comment]
Module added, layout set but no functionality in navigation. Currently using images instead of videos. Titles, image links and text are all hardcoded into BuildRobot/index.js.
