### ISSUE TITLE
Update troubleshooting docs

### ISSUE THREAD

**Issue by chico** [codeandrobots/codeandrobots-app#7]
1. Create a new TROUBLESHOOTING.md doc and move contents from https://github.com/codeandrobots/codeandrobots-app#troubleshooting and https://github.com/codeandrobots/codeandrobots-app/blob/master/SETUP_WINDOWS.md#troubleshooting into it

2. Replace https://github.com/codeandrobots/codeandrobots-app#troubleshooting and https://github.com/codeandrobots/codeandrobots-app/blob/master/SETUP_WINDOWS.md#troubleshooting sections with a link that references the new TROUBLESHOOTING.md doc

3. Update TROUBLESHOOTING.md doc with latest workarounds including glog fix using `glog-0.3.4.zip` and iOS simulator fix.

**Comment by chico** [comment]
Here's the `glog-0.3.4.zip` file:
[glog-0.3.4.zip](https://github.com/codeandrobots/codeandrobots-app/files/3320286/glog-0.3.4.zip)

**Comment by OsosKP** [comment]
It'll all updated so I'll close this, but have a look to check my work obviously.
